### ISSUE TITLE
Error in rc.runs('single_dataset001', 1) 

### ISSUE THREAD

**Issue by Qifan94** [lfads/lfads-run-manager#10]
When I finished the python script, there was an error in matlab.

rc.runs('single_dataset001', 1) 
 Index in position 1 exceeds array bounds (must not exceed 1).

**Comment by Qifan94** [comment]
Use rc.runs(1) instead.

**Comment by djoshea** [comment]
Hey just fyi, this was a typo. Either it should be `rc.runs(1)` as you said or `rc.findRuns('single_dataset001', 1)`, which I've changed it to in fab0317.

**Comment by Qifan94** [comment]
THANKS!
