### ISSUE TITLE
Minimum CUDA version

### ISSUE THREAD

**Issue by jrm2107** [lfads/lfads-run-manager#17]
I have a slightly older GPU, and I was hoping to get this package to work.  It gives me a tmux error, so I'm assuming that it has something to do with compatibility with my GPU.  Is there a minimum CUDA version that you require to run LFADS?

**Comment by djoshea** [comment]
Sorry for the delayed reply. Your best resource is this table https://www.tensorflow.org/install/source#linux which lists the required CUDA version for each tensorflow version. We've tried to keep the LFADS implementation reasonably up to date with versions of Tensorflow, but the code doesn't use too many recent features in the language, so the changes have been cosmetic. If you run into issues with older Tensorflow versions, you could probably fix up the syntax issues if you're comfortable with Python.

Alternatively, you could try the JAX implementation, which might be more forgiving of other CUDA versions (I'm not sure). https://github.com/google-research/computation-thru-dynamics

Hope this helps!
