### ISSUE TITLE
loading matrix in Lorenz dataset

### ISSUE THREAD

**Issue by lyprince** [lfads/lfads-run-manager#18]
Feel free to close this if I've got this wrong (I'm a bit out of practice with Matlab but ran parts of this in octave), but I don't think the way you generate the loading matrix for the Lorenz datasets is working as intended.

Line 70 in Utils/generateDemoDatasets.m:
`W = sort((rand(s, nCh, D)+1) .* sign(randn(s, nCh, D)), 1); % N x 3`

would surely produce a weight matrix where all columns are sorted in ascending order, something like e.g.,

![image](https://user-images.githubusercontent.com/9449909/58903846-5e03b200-86d4-11e9-9384-455588383491.png)

rather than a weight matrix that sorts according to the order of the first column only, e.g.,

![image](https://user-images.githubusercontent.com/9449909/58903955-9c00d600-86d4-11e9-8a07-16ee381e41ea.png)

which I'm guessing is how you would get 'neurons sorted according to their weighting for the first Lorenz dimension'

**Comment by djoshea** [comment]
Great catch! Thanks.
